### ISSUE TITLE
fakecygpty fails with 'Failed to open slave pty: Bad address'

### ISSUE THREAD

**Issue by bleggett** [d5884/fakecygpty#1]
OS: Win 10 64
Cygwin GCC version: 5.4.0
Emacs version: 24.5.1

First off, thanks for doing this, I really, really want Cygwin bash in emacs's 'term' and was happy to find this repo.

Compiled fakecygpty and qkill. Verified that the .el file was loaded and that fakecygpty-activate was enabled. Verified that emacs is running as admin so permissions problems should be moot.

`M-x term` gives 'Failed to open slave pty: Bad address'.

Am I missing something or has Win 10/Cygwin broken something?

**Comment by d5884** [comment]
I have only Windows 7 64bit envrionment, so I cannot test on Windows 10, so it's possibility of environment dependent bug.
1. Please tell me your cygwin version. (result of `cygcheck -V`)
2.  Try original version of fakecygpty ([Shougo:fakecygpty](https://github.com/Shougo/fakecygpty) or [trueroad:fakecygpty](https://github.com/trueroad/fakecygpty))

**Comment by d5884** [comment]
Oh, sorry. My cygwin environment is so old, and this bug was reproduced after updating to the lastest version.

**Comment by d5884** [comment]
Fixed. Please check it.

**Comment by bleggett** [comment]
Beautiful! It works. Thanks much!
