### ISSUE TITLE
Compiling under MSYS2 64bit

### ISSUE THREAD

**Issue by technician77** [d5884/fakecygpty#2]
Well, I have no conding skills but I manged to compile under cygwin successfully. Now I would like to switch to MSYS2 but there seem to be problems in compiling. I use the mingw-w64-x86_64-toolchain.

This is the compile error. It seems terminos.h is not there and I've seen other sources that suggest that termios.h is not supported by MSYS2 at all.

Is there any solution that you suggest? It would be sad to gain the advantages of MSYS2 over cygwin at the cost of a broken shell in emacs.
```
config.status: executing depfiles commands
gcc -DHAVE_CONFIG_H -I.    -D_GNU_SOURCE -g -O2 -MT fakecygpty.o -MD -MP -MF .deps/fakecygpty.Tpo -c -o fakecygpty.o fakecygpty.c
fakecygpty.c:68:10: fatal error: termios.h: No such file or directory
 #include <termios.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:395: fakecygpty.o] Fehler 1

```
With kind regards,
tech77

**Comment by technician77** [comment]
Installed msys2-devel and compiled under msys2 instead of mingw. That did the trick. But would it be possible to rewrite fakecygpty so it would compile under mingw64? If I'm correct that would produce a native executable.

**Comment by wusi524888** [comment]
how to solve the problem? sincecly waiting for your help.

**Comment by ankushbhagats** [comment]
You need to install package: `msys2-runtime-devel` using:
```
pacman -S msys2-runtime-devel
```

then have to create symlink in /mingw64/include to detect all header files from /usr/include (for mingw toolchain)
```
ln -s /usr/include /mingw64/include/usr
```

now it's all set.
